import json
import re
from collections import Counter, defaultdict
from pathlib import Path

from cadac_cpp.extract_cpp import PROGRAM_DIRS

_NUMBER = re.compile(r"^[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?$")


def descriptions_in(text: str) -> dict[str, str]:
    counts: dict[str, Counter[str]] = defaultdict(Counter)
    for line in text.splitlines():
        for name, sentence in _inits(_strip_comment(line)):
            counts[name][sentence] += 1
    return {name: _pick(counter) for name, counter in counts.items()}


def shared_descriptions(glossary: dict[str, dict[str, str]]) -> dict[str, str]:
    counts: dict[str, Counter[str]] = defaultdict(Counter)
    for table in glossary.values():
        for name, sentence in table.items():
            counts[name][sentence] += 1
    return {name: _pick(counter) for name, counter in counts.items()}


def render_variable_help_ts(glossary: dict[str, dict[str, str]]) -> str:
    lines = [
        "// Generated by cadac_cpp.field_help from CADAC Variable::init definitions.",
        "export const variableHelp: Record<string, Record<string, string>> = {",
    ]
    for program in sorted(glossary):
        lines.append(f"  {program}: {{")
        for name, sentence in sorted(glossary[program].items()):
            lines.append(f"    {_ts_key(name)}: {json.dumps(sentence, ensure_ascii=False)},")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    lines.append("export const sharedHelp: Record<string, string> = {")
    for name, sentence in sorted(shared_descriptions(glossary).items()):
        lines.append(f"  {_ts_key(name)}: {json.dumps(sentence, ensure_ascii=False)},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def _ts_key(name: str) -> str:
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        return name
    return json.dumps(name, ensure_ascii=False)


def build_glossary(root: Path) -> dict[str, dict[str, str]]:
    glossary: dict[str, dict[str, str]] = {}
    for program, rel in PROGRAM_DIRS.items():
        folder = root / rel
        chunks: list[str] = []
        for path in sorted(folder.rglob("*.cpp")):
            chunks.append(path.read_text(encoding="utf-8", errors="replace"))
        glossary[program.lower()] = descriptions_in("\n".join(chunks))
    return glossary


def _pick(counter: Counter[str]) -> str:
    best = max(counter.values())
    tied = [sentence for sentence, count in counter.items() if count == best]
    return min(tied, key=lambda sentence: (len(sentence), sentence))


def _strip_comment(line: str) -> str:
    out: list[str] = []
    in_string = False
    i = 0
    while i < len(line):
        char = line[i]
        if in_string:
            out.append(char)
            if char == "\\" and i + 1 < len(line):
                out.append(line[i + 1])
                i += 2
                continue
            if char == '"':
                in_string = False
        elif char == '"':
            in_string = True
            out.append(char)
        elif line.startswith("//", i):
            break
        else:
            out.append(char)
        i += 1
    return "".join(out)


def _inits(line: str):
    start = 0
    while True:
        i = line.find(".init(", start)
        if i < 0:
            return
        inner, end = _inside_parens(line, i + len(".init("))
        parsed = _definition(_split_args(inner))
        if parsed is not None:
            yield parsed
        start = end


def _inside_parens(line: str, open_at: int) -> tuple[str, int]:
    depth = 1
    in_string = False
    i = open_at
    while i < len(line) and depth:
        char = line[i]
        if in_string:
            if char == "\\" and i + 1 < len(line):
                i += 2
                continue
            if char == '"':
                in_string = False
        elif char == '"':
            in_string = True
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return line[open_at:i], i + 1
        i += 1
    return line[open_at:], len(line)


def _split_args(inner: str) -> list[str]:
    args: list[str] = []
    buf: list[str] = []
    in_string = False
    i = 0
    while i < len(inner):
        char = inner[i]
        if in_string:
            buf.append(char)
            if char == "\\" and i + 1 < len(inner):
                buf.append(inner[i + 1])
                i += 2
                continue
            if char == '"':
                in_string = False
        elif char == '"':
            in_string = True
            buf.append(char)
        elif char == ",":
            args.append("".join(buf).strip())
            buf = []
        else:
            buf.append(char)
        i += 1
    tail = "".join(buf).strip()
    if tail:
        args.append(tail)
    return args


def _definition(args: list[str]) -> tuple[str, str] | None:
    if not args:
        return None
    name = _unquote(args[0])
    if not name:
        return None
    rest = args[1:]
    if rest and _unquote(rest[0]) == "int":
        if len(rest) < 3:
            return None
        sentence = _unquote(rest[2])
    else:
        index = 0
        while index < len(rest) and _NUMBER.match(rest[index].strip()):
            index += 1
        if index >= len(rest):
            return None
        sentence = _unquote(rest[index])
    if sentence is None:
        return None
    return name, sentence


def _unquote(token: str) -> str | None:
    token = token.strip()
    if len(token) < 2 or token[0] != '"' or token[-1] != '"':
        return None
    body = token[1:-1]
    return body.replace('\\"', '"').replace("\\\\", "\\")
